import { createServer, type Server } from 'node:http';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildApp } from '../../server/dist/app.js';
import { openDatabase } from '../../server/dist/db/connection.js';
import { runMigrations } from '../../server/dist/db/migrate.js';
import { JSDOM } from 'jsdom';
import { afterEach, expect, it, vi } from 'vitest';
import WebSocket from 'ws';

let provider: Server | undefined;
let server: Awaited<ReturnType<typeof buildApp>> | undefined;
let db: ReturnType<typeof openDatabase> | undefined;
let dataDir: string | undefined;
let dom: JSDOM | undefined;
afterEach(async () => {
  await server?.close();
  await new Promise<void>((resolve) => provider?.close(() => resolve()) ?? resolve());
  db?.close();
  dom?.window.close();
  if (dataDir) rmSync(dataDir, { recursive: true, force: true });
  vi.unstubAllGlobals();
});

it('renders the authenticated provider-backed DM and restores its reply after remount', async () => {
  provider = createServer(async (req, res) => {
    if (req.url !== '/v1/chat/completions') { res.writeHead(404).end(); return; }
    const chunks: Buffer[] = [];
    for await (const chunk of req) chunks.push(chunk as Buffer);
    const messages = JSON.parse(Buffer.concat(chunks).toString()).messages as { content: string }[];
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ choices: [{ message: { content: `Provider says: ${messages.at(-1)?.content}` }, finish_reason: 'stop' }] }));
  });
  await new Promise<void>((resolve) => provider!.listen(0, '127.0.0.1', resolve));
  const providerAddress = provider.address();
  if (!providerAddress || typeof providerAddress === 'string') throw new Error('provider address');
  dataDir = mkdtempSync(join(tmpdir(), 'opencrew-app-ui-'));
  db = openDatabase(dataDir); runMigrations(db);
  server = await buildApp({ db });
  await server.listen({ port: 0, host: '127.0.0.1' });
  const serverAddress = server.server.address();
  if (!serverAddress || typeof serverAddress === 'string') throw new Error('server address');
  dom = new JSDOM('<!doctype html><html><head></head><body><div id="root"></div></body></html>',
    { url: `http://127.0.0.1:${serverAddress.port}/`, pretendToBeVisual: true });
  const win = dom.window;
  Object.defineProperty(win, 'matchMedia', { value: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) });
  Object.defineProperty(win.HTMLElement.prototype, 'scrollIntoView', { value() {} });
  vi.stubGlobal('window', win); vi.stubGlobal('document', win.document);
  vi.stubGlobal('navigator', win.navigator); vi.stubGlobal('localStorage', win.localStorage);
  vi.stubGlobal('HTMLElement', win.HTMLElement); vi.stubGlobal('HTMLDivElement', win.HTMLDivElement);
  vi.stubGlobal('Node', win.Node); vi.stubGlobal('Text', win.Text);
  vi.stubGlobal('MutationObserver', win.MutationObserver); vi.stubGlobal('WebSocket', WebSocket);
  vi.resetModules();
  const { default: App } = await import('../src/App');
  const { AuthGate } = await import('../src/features/auth/AuthGate');
  const { render, fireEvent, within, waitFor } = await import('@testing-library/react');
  const React = await import('react');
  const UI = () => React.createElement(AuthGate, null, React.createElement(App));
  const page = within(win.document.body);
  const view = render(React.createElement(UI), { container: win.document.getElementById('root')! });
  await page.findByRole('heading', { name: 'Create first admin' });
  fireEvent.change(page.getByLabelText('Name'), { target: { value: 'Owner' } });
  fireEvent.change(page.getByLabelText('Email'), { target: { value: 'owner@example.test' } });
  fireEvent.change(page.getByLabelText('Password'), { target: { value: 'test-password-1' } });
  fireEvent.click(page.getByRole('button', { name: 'Create admin' }));
  await page.findByRole('heading', { name: 'Connect a real provider' });
  expect(win.localStorage.getItem('opencrew:session')).toBeTruthy();
  fireEvent.change(page.getByLabelText('Provider'), { target: { value: 'openai-compatible' } });
  fireEvent.change(page.getByLabelText('Provider ID'), { target: { value: 'mock' } });
  fireEvent.change(page.getByLabelText('API key'), { target: { value: 'test-key' } });
  fireEvent.change(page.getByLabelText('Base URL'), { target: { value: `http://127.0.0.1:${providerAddress.port}/v1` } });
  fireEvent.click(page.getByRole('button', { name: 'Save provider' }));
  await page.findByRole('heading', { name: 'Your crew' });
  fireEvent.click(page.getByRole('button', { name: 'Create agent' }));
  const dialog = within(page.getByRole('dialog', { name: 'Create an agent' }));
  fireEvent.change(dialog.getByRole('textbox', { name: /Name/ }), { target: { value: 'Echo' } });
  fireEvent.change(dialog.getByRole('textbox', { name: /Role/ }), { target: { value: 'Assistant' } });
  fireEvent.change(dialog.getByRole('textbox', { name: 'Model ID' }), { target: { value: 'test-model' } });
  fireEvent.click(dialog.getByRole('button', { name: /Create agent/ }));
  const composer = await page.findByRole('combobox', { name: 'Message Echo' });
  Object.defineProperty(composer, 'innerText', { configurable: true, value: 'Hello' });
  fireEvent.input(composer);
  await waitFor(() => expect(page.getByRole('button', { name: 'Send message' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(page.getByRole('button', { name: 'Send message' }));
  await page.findByText('Provider says: Hello');
  view.unmount();
  const refreshedRoot = win.document.createElement('div');
  win.document.body.appendChild(refreshedRoot);
  render(React.createElement(UI), { container: refreshedRoot });
  await page.findByText('Provider says: Hello');
  expect(db.prepare('SELECT COUNT(*) AS n FROM messages').get()).toEqual({ n: 2 });
});
